### ISSUE TITLE
Kings golf club

### ISSUE THREAD

**Issue by TheImmortalKing** [GDcheeriosYT/Gentrys-Quest-Ursina#7]
golf club weapon named after me!

**Comment by GDcheeriosYT** [comment]
Give me some details.

star rating 1-5
base speed(how many seconds it takes to use it again)
base attack keep it between 10-70 (relatively close to star rating)
range (how far it can reach) avg is 1
and attack style

**Comment by TheImmortalKing** [comment]
star rating 3
base speed 1.5
base attack 37
range 2.3
attack style swing (either up and down or like the pen)

**Comment by GDcheeriosYT** [comment]
A little OP right now but it's implemented!
